-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------

create function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  t text;
begin
  for t in
    select unnest(array[
      'profiles', 'admin_accounts', 'organizations', 'customer_accounts',
      'contractor_accounts', 'contractor_rates', 'contractor_insurance',
      'mower_models', 'service_plans', 'properties', 'customer_subscriptions',
      'customer_mowers', 'service_requests', 'service_schedules', 'appointments',
      'work_orders', 'job_assignments', 'quote_requests', 'invoices', 'payments',
      'complaints'
    ])
  loop
    execute format(
      'create trigger set_updated_at before update on %I for each row execute function set_updated_at();',
      t
    );
  end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- New auth.users -> profiles
-- ---------------------------------------------------------------------------

create function handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, new.raw_user_meta_data ->> 'full_name');
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- ---------------------------------------------------------------------------
-- Invoice / work_order timing logic
--
-- 1. Inserting a work_order (whether created directly or generated by the
--    service_schedule job) immediately creates a matching draft invoice.
-- 2. The invoice is only flipped to 'sent' once the work_order's status
--    transitions to 'completed'. Enforced as a trigger so this holds no
--    matter what path changes the work order's status.
-- ---------------------------------------------------------------------------

create function create_draft_invoice_for_work_order()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  new_invoice_id uuid;
begin
  insert into invoices (customer_account_id, work_order_id, status, subtotal, tax_amount, total_amount)
  values (new.customer_account_id, new.id, 'draft', new.price, 0, new.price)
  returning id into new_invoice_id;

  insert into invoice_items (invoice_id, description, quantity, unit_price)
  values (new_invoice_id, new.service_type::text, 1, new.price);

  return new;
end;
$$;

create trigger work_order_create_draft_invoice
  after insert on work_orders
  for each row execute function create_draft_invoice_for_work_order();

create function mark_invoice_sent_on_work_order_completed()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.status = 'completed' and old.status is distinct from 'completed' then
    update invoices
    set status = 'sent', sent_at = now()
    where work_order_id = new.id and status = 'draft';
  end if;
  return new;
end;
$$;

create trigger work_order_mark_invoice_sent
  after update of status on work_orders
  for each row execute function mark_invoice_sent_on_work_order_completed();

-- ---------------------------------------------------------------------------
-- Audit logging
-- ---------------------------------------------------------------------------

create function log_audit_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into audit_logs (actor_profile_id, action, table_name, record_id, old_values, new_values)
  values (
    auth.uid(),
    tg_op,
    tg_table_name,
    coalesce(new.id, old.id),
    case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end,
    case when tg_op in ('UPDATE', 'INSERT') then to_jsonb(new) else null end
  );
  return coalesce(new, old);
end;
$$;

do $$
declare
  t text;
begin
  for t in
    select unnest(array[
      'customer_accounts', 'contractor_accounts', 'admin_accounts',
      'invoices', 'payments', 'work_orders', 'job_assignments'
    ])
  loop
    execute format(
      'create trigger audit_log after insert or update or delete on %I for each row execute function log_audit_event();',
      t
    );
  end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- RLS helper functions (security definer so they can check membership in
-- admin_accounts / customer_accounts / contractor_accounts without being
-- blocked by those tables' own RLS policies, avoiding policy recursion).
-- ---------------------------------------------------------------------------

create function is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from admin_accounts
    where profile_id = auth.uid() and status = 'active'
  );
$$;

create function is_contractor()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from contractor_accounts
    where profile_id = auth.uid() and status = 'active'
  );
$$;
